### PR TITLE
Issue #4400 Fixed ObserveChanges plugin memory leak

### LINKED ISSUE #4400: ObserveChanges plugin causing memory leak
### Description

Our Handsontable had a memory leak for some reason and couldn't work out why. Looking at the memory profile we noticed that the `afterLoadData` hook was being fired even though we didn't specify it in the options. We noticed it was being added by the ObserveChanges plugin but we don't have it enabled and is supposed to be disabled be default. We explicitly disabled it in our table options and fixed our memory issue. Not sure exactly what was causing it but something to do with that plugin. We added it to a jsfiddle example and it caused it to leak memory too.

### Steps to reproduce

1. Add `observeChanges: true` to your table options
2. Recursively load data
3. Leak memory

### Demo

http://jsfiddle.net/Lp4qn55v/745/

### Your environment
* Handsontable version: 1.2.0
* Browser Name and version: Google Chrome Version 59.0.3071.115
* Operating System: Windows 10

### PR DESCRIPTION
**Pull request by jeremy-smith-maco**
### Context

Fixes #4400 - ObserveChanges plugin causing a memory leak (which as actually caused by the JSON patch library)

### How has this been tested?

Tested it locally in our own project and ensured all Handsontable tests still pass.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #4400 

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Can I just ask to add a test @jeremy-smith-maco ?

**Comment by jeremy-smith-maco** [comment]
The file I edited is an external library that has been copied into the project. I would have to directly test the library itself which has its own tests in that library's project. I don't think you can access the variable I altered in this PR without testing the library itself.

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco 

I am not able to add the `ready for review` badge for PR that changes the code and do not provide tests.
Please let me know if you would like to add them.

**Comment by jeremy-smith-maco** [comment]
I attempted to make a test for the change I made but it doesn't seem like I can actually test the change I made because of how the library is written. It only gives you access to several methods of which none of them I can use to test that this change works as expected. 

It updates an array inside of the library which is not accessible outside of the library as it doesn't export it or any functions that can access that array directly.

File: lib/jsonpatch/json-patch-duplex.js [hunk 1]
```diff
@@ -330,6 +330,10 @@ var jsonpatch;
             generate(observer);
             clearTimeout(observer.next);
             removeObserverFromMirror(mirror, observer);
+            if (mirror.observers.length === 0)
+            {
```
Comment (pnowak) [inline lib/jsonpatch/json-patch-duplex.js]: Incorrect format - braces must be on this same line after the preceding closing brace.

**Comment by jeremy-smith-maco** [comment]
Fied @pnowak

**Comment by jeremy-smith-maco** [comment]
Will this ever get merged? 😆

**Comment by AMBudnik** [comment]
Sorry @jeremy-smith-maco we've added a lot of confusing updates to the PR...
If not before the next release we will review the code before another one. We have changed the way we manage tasks so now it can be really messy.

**Comment by swistach** [comment]
Hi @jeremy-smith-maco.
We discussed `lib/json-patch/json-patch-duplex` inside core team. In our opinion, it will be better to use npm package: https://github.com/Starcounter-Jack/JSON-Patch instead of out-of-date duplicate from our repository. So, I cannot accept your PR.
But if you would like to help us with this, what I mentioned above, then feel free to send us new PR.

**Comment by jeremy-smith-maco** [comment]
Looking at their latest code it seems like this still might be an issue. I'm not sure if it's an issue with their library or its' purpose does not fit with how handsontable uses it but I think it is worth testing against my test case in the original GitHub issue: https://github.com/handsontable/handsontable/issues/4400

**Comment by swistach** [comment]
I agree this might be an issue in Starcounter-Jack/JSON-Patch. But then, we should send them PR with fix suggestion.
I think we should back to your test case with updated dependency.

**Comment by jeremy-smith-maco** [comment]
That would be ideal. We are currently using this fix locally in our project otherwise we run out of memory too fast.

**Comment by pnowak** [comment]
Hi @jeremy-smith-maco 
You right, the memory leak still continues. Thanks for your investigate and fix.

**Comment by swistach** [comment]
This fix looks good to me as a temporary solution. Thank you @jeremy-smith-maco!
