### PR TITLE
[RTL] Fix positioning of the manual column move handlers

### LINKED ISSUE #8833: [RTL] ManualColumnMove
### Description

For RTL, it needs to fix:
* The line between columns is drawn incorrectly
* The shadow of the column is drawn incorrectly
* The position of the dragged column is calculated the same way as for LTR (it don't detect that columns are printed in inverted order)

### How to reproduce

1. use this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/068ec844ef6004d24ee6cb863462e8982d5a51f3/vanilla/configurations.js#L811-L820)
```js
{
    data: Handsontable.helper.createSpreadsheetData(200, 20),
    width: '100%',
    height: 320,
    rowHeaders: true,
    colHeaders: true,
    colWidths: 100,
    manualColumnMove: true,
    licenseKey: 'non-commercial-and-evaluation'
}
```
2. click and drag the column `L`
3. move over `K`, then `J`, then `I`, then `H`, then `G`
4. release drag over column `G`
5. Incorrectly, the column is moved into column `H`

https://user-images.githubusercontent.com/2893099/136024693-32fc29d7-239d-4784-a131-90291734fb28.mp4

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR fixes the _ManualColumnMove_ plugin that does not work in RTL mode. The change fixes the handler positioning.

LTR:
Kapture 2022-01-28 at 10 19 47

RTL:
Kapture 2022-01-28 at 10 20 37

~For reviewer: The tests do not pass due to some weird bug in the CI. The tests pass locally and within another PR that contained the proposed changes (https://github.com/handsontable/handsontable/pull/9172).~

_[skip changelog]_

### How has this been tested?

I tested the changes locally. I focused on testing the positioning of the backlight and guideline elements in cases where Handsontable is initialized with and without defining table size. With and without scrolling. Moreover, I added tons of new E2E tests.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. resolves #8833

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Comment by Siemienik** [comment]
I've dismissed my review request because of the failing tests, would you mind rerequesting when they pass?

File: handsontable/src/plugins/manualColumnMove/manualColumnMove.js [hunk 1]
```diff
@@ -406,53 +406,59 @@ export class ManualColumnMove extends BasePlugin {
...
-        priv.coords += 1;
-      }
+    if (this.hot.isRtl()) {
+      const rootWindow = this.hot.rootWindow;
+      const containerWidth = outerWidth(this.hot.rootElement);
+      const gridMostRightPos = rootWindow.innerWidth - priv.rootElementOffset - containerWidth;
+
+      mouseOffsetStart = rootWindow.innerWidth - priv.target.eventPageX - gridMostRightPos -
+        (scrollableElement.scrollX === void 0 ? scrollStart : 0);
+    } else {
```
Comment (jansiegel) [inline handsontable/src/plugins/manualColumnMove/manualColumnMove.js:426]: An empty line between `else` would be nice.

File: handsontable/src/plugins/manualColumnMove/manualColumnMove.js [hunk 2]
```diff
@@ -406,53 +406,59 @@ export class ManualColumnMove extends BasePlugin {
...
+      mouseOffsetStart = priv.target.eventPageX -
+        (priv.rootElementOffset - (scrollableElement.scrollX === void 0 ? scrollStart : 0));
     }
 
     if (priv.hasRowHeaders) {
       rowHeaderWidth = this.hot.view.wt.wtOverlays.inlineStartOverlay.clone.wtTable.getColumnHeader(-1).offsetWidth;
     }
-    if (this.isFixedColumnsStart(priv.coords)) {
-      tdOffsetLeft += scrollLeft;
+    if (this.isFixedColumnsStart(priv.hoveredColumn)) {
```
Comment (jansiegel) [inline handsontable/src/plugins/manualColumnMove/manualColumnMove.js:434]: An empty line between the  `if`s would be nice, as well as an empty line after the second `if`. (I know it's nitpicking and that most of the code here is not new, so I leave it up to you)

**Review by jansiegel — APPROVED** [review]
