### PR TITLE
Fix a problem with keyboard navigation and scrolling on window-scrolled instances.

### LINKED ISSUE #3070: Table scrolling bug when scrollable element is window
When we try to scroll table by selecting cell and pressing arrow key then scroll is not applied to the scrollable element. This occurs only if table has scrollable element as window object.

scrolling

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
The problem described in handsontable/dev-handsontable#49 is most probably caused by a fix made for #3070. 
However, that fix seems to be no longer working (the drag-to-scroll feature for window-scrolled instances does not work currently).

This PR aims to:
- Fix handsontable/dev-handsontable#49
- Make the "drag to scroll" functionality work for both element-scrolled and window-scrolled instances (so, in a while, re-fix #3070)

### How has this been tested?
- Tested manually
- Added test cases for element-scrolled instances

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. handsontable/dev-handsontable#49
2. #3070

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
Note for the reviewer:
I couldn't figure out how to test drag-to-scroll on a window-scrolled instance (the problem is simulating mouse movement outside of the window), so I added just the tests for the element-scrolled ones. If you have any ideas on how to test those, I'll gladly add them.

File: handsontable/src/plugins/dragToScroll/dragToScroll.js [hunk 1]
```diff
@@ -97,9 +97,15 @@ export class DragToScroll extends BasePlugin {
   /**
    * Sets the value of the visible element.
    *
-   * @param {DOMRect} boundaries An object with coordinates compatible with DOMRect.
+   * @param {DOMRect|{left: number, right: number, top: number, bottom: number}} [boundaries] An object with
+   * coordinates. Contains the window boundaries by default. The object is compatible with DOMRect.
    */
-  setBoundaries(boundaries) {
+  setBoundaries(boundaries = {
```
Comment (budnix) [inline handsontable/src/plugins/dragToScroll/dragToScroll.js:103]: Can I ask to update the types as well? https://github.com/handsontable/handsontable/blob/feature/dev-issue-49/handsontable/types/plugins/dragToScroll/dragToScroll.d.ts#L12

**Review by budnix — DISMISSED** [review]

**Review by budnix — APPROVED** [review]
